---
# handlers file for ansible-role-uwsgi

- name: Start Emperor
  service:
    state: started
    name: emperor

- name: Stop Emperor
  service:
    state: stopped
    name: emperor

- name: Restart Emperor
  service:
    state: restarted
    name: emperor

- name: Reload Emperor Systemd
  systemd:
    state: restarted
    daemon_reload: yes
    name: emperor
  when: ansible_service_mgr == 'systemd'
  listen: Reload Emperor

- name: Reload Emperor Initd
  service:
    state: reloaded
    name: emperor
  listen: Reload Emperor
